autoload:
  yahoo:
    name:           yahoo
    path:           %SF_PLUGINS_DIR%/ysfOpenPlugin/lib/vendor/yahoo
    recursive:      true

  openid:
    name:           openid
    path:           %SF_PLUGINS_DIR%/ysfOpenPlugin/lib/vendor/openid
    recursive:      true

  oauth:
    name:           oauth
    path:           %SF_PLUGINS_DIR%/ysfOpenPlugin/lib/vendor/oauth
    recursive:      true

  opensocial:
    name:           opensocial
    path:           %SF_PLUGINS_DIR%/ysfOpenPlugin/lib/vendor/opensocial
    recursive:      true
